spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 261219
    url: jdbc:mysql://localhost:3306/usercenter

server:
  port: 8080


